### ISSUE TITLE
Create new database, migrations are failing

### ISSUE THREAD

**Issue by Jandev** [jfversluis/CfpExchange#60]
I just deleted my database and created a new one. Afterward, I did an `Update-Database` and saw a lot of errors occurring. Because of this, the site isn't able to load anymore.

It's a bit much to copy the complete error over here, but this is an excerpt of the first part.
```
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (31ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
      VALUES (N'20180609180239_AddedExpensesToCfpAndUserStuff', N'2.0.2-rtm-10011');
failApplication startup exception: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'CfpDecisionDate'.
Invalid column name 'DuplicateOfId'.
Invalid column name 'EventTags'.
Invalid column name 'EventTimezone'.
Invalid column name 'EventTwitterHandle'.
Invalid column name 'ProvidesAccommodation'.
Invalid column name 'ProvidesTravelAssistance'.
Invalid column name 'Remarks'.
Invalid column name 'Slug'.
Invalid column name 'CfpDecisionDate'.
Invalid column name 'DuplicateOfId'.
Invalid column name 'EventTags'.
Invalid column name 'EventTimezone'.
Invalid column name 'EventTwitterHandle'.
Invalid column name 'ProvidesAccommodation'.
Invalid column name 'ProvidesTravelAssistance'.
Invalid column name 'Remarks'.
Invalid column name 'Slug'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at CfpExchange.Data.CfpContextExtensions.EnsureSeeded(CfpContext context) in D:\Projecten\CfpExchange\CfpExchange\Data\CfpContext.cs:line 149
   at CfpExchange.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\Projecten\CfpExchange\CfpExchange\Startup.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
: CfpExchange.Startup[0]
      Failed to migrate or seed database
System.Data.SqlClient.SqlException (0x80131904): ALTER TABLE DROP COLUMN failed because column 'ProvidedExpenses' does not exist in table 'Cfps'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at CfpExchange.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\Projecten\CfpExchange\CfpExchange\Startup.cs:line 88
ClientConnectionId:3f7aba2d-dfb7-423f-ad89-795b800cdad7
Error Number:4924,State:1,Class:16
Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20180612071509_TravelAndAccommodation'.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (707ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DECLARE @var0 sysname;
      SELECT @var0 = [d].[name]
      FROM [sys].[default_constraints] [d]
      INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
      WHERE ([d].[parent_object_id] = OBJECT_ID(N'Cfps') AND [c].[name] = N'ProvidedExpenses');
      IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Cfps] DROP CONSTRAINT [' + @var0 + '];');
      ALTER TABLE [Cfps] DROP COLUMN [ProvidedExpenses];
System.Data.SqlClient.SqlException (0x80131904): ALTER TABLE DROP COLUMN failed because column 'ProvidedExpenses' does not exist in table 'Cfps'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:3f7aba2d-dfb7-423f-ad89-795b800cdad7
Error Number:4924,State:1,Class:16
```

I'm not sure why this occurs as I haven't seen this before in this project.

By the way, this also happens when doing the auto-migrations whenever the site hits the database. Can only reproduce this on an actual SQL Server. When using the `services.AddDbContext<CfpContext>(opt => opt.UseInMemoryDatabase("Cfps"));` I don't see this error occurring.

**Comment by Jandev** [comment]
Just tried it on the `master` branch with an empty database, same result.

**Repro**
1. Create a new, empty database
2. Modify the connectionstring in the `appsettings.json` to point to this database.
```
  "ConnectionStrings": {
    "CfpExchangeDb": "Data Source=tcp:myDatabaseServer.database.windows.net,1433;Initial Catalog=myEmptyDatabase;User Id=mySqlAdministrator@myDatabaseServer;Password=myPassword"
  },
```
3. Change the first `Startup.ConfigureServices()` to make sure you're pointing to a real database.
```
/*if (_environment.IsDevelopment())
	services.AddDbContext<CfpContext>(opt => opt.UseInMemoryDatabase("Cfps"));
else*/
	services.AddDbContext<CfpContext>(opt => opt.UseSqlServer(Configuration.GetConnectionString("CfpExchangeDb")));
```
4. Run the `Update-Database` command in the Package Manager Console with the `CfpExchange` as a Default Project

**Comment by Jandev** [comment]
Found the problem!

>       Applying migration '20180612071509_TravelAndAccommodation'.
> fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
>       Failed executing DbCommand (31ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
>       DECLARE @var0 sysname;
>       SELECT @var0 = [d].[name]
>       FROM [sys].[default_constraints] [d]
>       INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
>       WHERE ([d].[parent_object_id] = OBJECT_ID(N'Cfps') AND [c].[name] = N'ProvidedExpenses');
>       IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [Cfps] DROP CONSTRAINT [' + @var0 + '];');
>       ALTER TABLE [Cfps] DROP COLUMN [ProvidedExpenses];
> System.Data.SqlClient.SqlException (0x80131904): ALTER TABLE DROP COLUMN failed because column 'ProvidedExpenses' does not exist in table 'Cfps'.

The migration `20180612071509_TravelAndAccommodation` is trying to delete the column `ProvidedExpenses`, but this one does not exist.

The column is mentioned in the `AddedExpensesToCfpAndUserStuff` designer class, but never added to the actual table.
Adding the column manually to the table appears to help
```sql
ALTER TABLE Cfps 
ADD ProvidedExpenses INT;
```
But that's not much of a solution of course.
